/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as DemoMiniQueryPostsIndexImport } from './routes/demo.mini-query.posts.index'
import { Route as DemoMiniQueryPostsPostPostIdImport } from './routes/demo.mini-query.posts.post.$postId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const DemoMiniQueryPostsIndexRoute = DemoMiniQueryPostsIndexImport.update({
  id: '/demo/mini-query/posts/',
  path: '/demo/mini-query/posts/',
  getParentRoute: () => rootRoute,
} as any)

const DemoMiniQueryPostsPostPostIdRoute =
  DemoMiniQueryPostsPostPostIdImport.update({
    id: '/demo/mini-query/posts/post/$postId',
    path: '/demo/mini-query/posts/post/$postId',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/demo/mini-query/posts/': {
      id: '/demo/mini-query/posts/'
      path: '/demo/mini-query/posts'
      fullPath: '/demo/mini-query/posts'
      preLoaderRoute: typeof DemoMiniQueryPostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/demo/mini-query/posts/post/$postId': {
      id: '/demo/mini-query/posts/post/$postId'
      path: '/demo/mini-query/posts/post/$postId'
      fullPath: '/demo/mini-query/posts/post/$postId'
      preLoaderRoute: typeof DemoMiniQueryPostsPostPostIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/mini-query/posts': typeof DemoMiniQueryPostsIndexRoute
  '/demo/mini-query/posts/post/$postId': typeof DemoMiniQueryPostsPostPostIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/mini-query/posts': typeof DemoMiniQueryPostsIndexRoute
  '/demo/mini-query/posts/post/$postId': typeof DemoMiniQueryPostsPostPostIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/mini-query/posts/': typeof DemoMiniQueryPostsIndexRoute
  '/demo/mini-query/posts/post/$postId': typeof DemoMiniQueryPostsPostPostIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/demo/mini-query/posts'
    | '/demo/mini-query/posts/post/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/demo/mini-query/posts'
    | '/demo/mini-query/posts/post/$postId'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/demo/mini-query/posts/'
    | '/demo/mini-query/posts/post/$postId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoMiniQueryPostsIndexRoute: typeof DemoMiniQueryPostsIndexRoute
  DemoMiniQueryPostsPostPostIdRoute: typeof DemoMiniQueryPostsPostPostIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoMiniQueryPostsIndexRoute: DemoMiniQueryPostsIndexRoute,
  DemoMiniQueryPostsPostPostIdRoute: DemoMiniQueryPostsPostPostIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/demo/tanstack-query",
        "/demo/mini-query/posts/",
        "/demo/mini-query/posts/post/$postId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/demo/mini-query/posts/": {
      "filePath": "demo.mini-query.posts.index.tsx"
    },
    "/demo/mini-query/posts/post/$postId": {
      "filePath": "demo.mini-query.posts.post.$postId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
